##### Numpy

In [1]:
#zaimportuj odpowiedni pakiet do pracy z wektorami i macierzami
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#wektor ar
ar = np.array([1,2,-3,6,7,-10,88,43,-98,17,39,45])
ar

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45])

In [3]:
#doklej do wektora ar wartości [4,5,9,10,23,-14,55,13]
ar2 = np.array([4,5,9,10,23,-14,55,13])

In [4]:
wektorki = np.concatenate((ar, ar2))

In [5]:
wektorki

array([  1,   2,  -3,   6,   7, -10,  88,  43, -98,  17,  39,  45,   4,
         5,   9,  10,  23, -14,  55,  13])

In [6]:
#znajdz index dla wartości 9 - użyj odpowiedniej funkcji
wektorki.tolist().index(9)

14

In [7]:
#znajdź indeksy dla wartości mniejszych od zera - użyj odpowiedniej funkcji
wektorki < 0

array([False, False,  True, False, False,  True, False, False,  True,
       False, False, False, False, False, False, False, False,  True,
       False, False], dtype=bool)

In [9]:
#wyświetl wartości mniejsze od zera
for value in wektorki:
    if value <0:
        print(value)

-3
-10
-98
-14


In [10]:
#policz średnią, zaokrąglij do jednego miejsca po przecinku
np.mean(wektorki)

12.1

In [11]:
#stwórz zmienną ar_abs, wektor wartości bezwględnych z wektora ar
ar_abs = max(np.absolute(ar))
ar_abs

98

In [12]:
#stwórz zmienną ar_p, wektor pierwiastków trzeciego stopnia z wektora ar_abs
ar_p = np.cbrt(ar_abs)
ar_p

4.6104362920584467

In [13]:
#zaokrąglij wektor ar_p do dwóch miejsc po przecinku
format(ar_p, '.2f')

'4.61'

In [15]:
#zsumuj zaokrąglony wektor ar_p i podnieś go do kwadratu, 
np.sum(ar_p)
ar_sq = np.square(ar_p)
ar_p



4.6104362920584467

In [16]:
type(ar_sq)

numpy.float64

In [17]:
#zmienną nazwij ar_sq, zmień typ tej zmiennej na liczbę całkowitą
ar_sq.astype(int)

21